version: "3.3"

services:
  db:
    image: postgres:13.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

  python_import:
      container_name: python_import
      build:
        context: .
        dockerfile: Dockerfile1
      depends_on:
        - db
      links:
        - "db:database"


  wiki:
    container_name: wiki
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - "db:database"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"